location            = "eastus"
rgname              = "webapppocdemoagu"
owner               = "Pod2"
createdby           = "AgustinDiaz"
project             = "webapptf"
pod                 = "2"
coe                 = "1"
deadline            = "2024-08-16"