name: Build and Deploy Docker Image

on:
  push:
    branches:
     # - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker image
      run: |
        docker buildx build --platform linux/amd64 --push \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/webapp:${{ github.sha }} \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/webapp:latest .
          
    - name: Azure Container Registry Logout
      run: |
        docker logout ${{ secrets.ACR_NAME }}.azurecr.io

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.WEBAPP_NAME }}
        images: ${{ secrets.ACR_NAME }}.azurecr.io/webapp:latest

