name: Build and Deploy to Azure Web App

on:
  push:
    branches:
     # - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: myacr.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t myacr.azurecr.io/myapp:${{ github.sha }} .
        docker push myacr.azurecr.io/myapp:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myWebApp'
        images: 'myacr.azurecr.io/myapp:${{ github.sha }}'
